name: reusable_copy_file2
description: copy file
on:
    workflow_call:

        inputs: 
            filename:
              required: true
              type: string
            path_source: 
              required: true
              type: string
            working_dir:
              required: true
              type: string
            target:
              required: true
              type: string

runs:
    using: "composite"
    steps:
        - name: making_directory
          run: |
                pwd
                mkdir -p $HOME/${{github.event.inputs.path_source}}
                mkdir -p $HOME/${{github.event.inputs.target}}
                echo "hello" > $HOME/${{github.event.inputs.path_source}}/hi.txt
                echo "hello" > $HOME/${{github.event.inputs.path_source}}/hi1.txt
          shell: bash

        - name: copying_file
          run: bash script.sh $HOME/${{github.event.inputs.path_source}}/${{github.event.inputs.filename}} $HOME/${{github.event.inputs.target}}/${{github.event.inputs.filename}}
          shell: bash
