name: reusable_copy_file2
description: copy file
inputs: 
    filename:
      required: true
      type: string
    path_source: 
      required: true
      type: string
    working_dir:
      required: true
      type: string
    target:
      required: true
      type: string

runs:
    using: "composite"
    steps:
        - name: making_directory
          run: |
                pwd
                sudo mkdir ${{ github.event.inputs.working_dir }}/source
                mkdir ${{ github.event.inputs.working_dir }}/target
                echo "hello" > ${{ github.event.inputs.working_dir }}/source/hi.txt
                echo "hello" > ${{ github.event.inputs.working_dir }}/source/hi1.txt
                echo "hello" > ${{ github.event.inputs.working_dir }}/source/hi2.txt
                echo "hello" > ${{ github.event.inputs.working_dir }}/source/hi3.txt
                echo "hello" > ${{ github.event.inputs.working_dir }}/source/hi4.txt
                echo "hello" > ${{ github.event.inputs.working_dir }}/source/hi5.txt
          shell: bash

        - name: copying_file
          run: bash ./script.sh ${{github.event.inputs.path_source}}/${{github.event.inputs.filename}} ${{github.event.inputs.working_dir}}/target
          shell: bash