name: explicit_call
permissions: write-all
on: 
    workflow_dispatch: 
        inputs:
            filename:
                required: true
                type: string
                description: what to copy
            path: 
                required: true
                type: string
                description: from where to copy



jobs:
    # env:
    #     workspace_git: ${{ github.workspace }}
    call_action:
        permissions: 
            actions: write
        uses: vasu43/prac2/.github/workflows/action.yml@main
        with: 
            filename: ${{github.event.inputs.filename}}
            path: ${{github.workspace}}/${{github.event.inputs.path}}
            working_dir: ${{github.workspace}}
                # target: ${{env.workspace_git}}
    
