name: Copy Local File

on: 
    workflow_dispatch: 
        inputs:
            
                filename:

                        required: true
                        type: string
                        description: what to copy
                path: 

                        required: true
                        type: string
                        description: from where to copy



jobs:   
    copy: 
        runs-on: ubuntu-latest
        steps:
            - name: make directory and files
              run: |
                    mkdir c:/source/
                    mkdir C:/target/
                    echo "hello" > c:/source/hi.txt
            - name: copy
              run: bash ../script.sh ${{github.event.inputs.path}}/${{github.event.inputs.filename}} 
              shell: bash
