name: Copy Local File

on: 
    workflow_dispatch: 
        inputs:
            
                filename:

                        required: true
                        type: string
                        description: what to copy
                path: 

                        required: true
                        type: string
                        description: from where to copy

env:
    workspace_git: ${{ github.workspace }}

jobs:   
    copy: 
        runs-on: ubuntu-latest
        steps:
            - name: make directory and files
              run: |
                    pwd
                    mkdir ${{ env.workspace_git }}/source
                    mkdir ${{ env.workspace_git }}/target
                    echo "hello" > ${{ env.workspace_git }}/source/hi.txt
                    echo "hello" > ${{ env.workspace_git }}/source/hi1.txt
                    echo "hello" > ${{ env.workspace_git }}/source/hi2.txt
                    echo "hello" > ${{ env.workspace_git }}/source/hi3.txt
                    echo "hello" > ${{ env.workspace_git }}/source/hi4.txt
                    echo "hello" > ${{ env.workspace_git }}/source/hi5.txt
                 
            - name: copy
              run: bash ../script.sh ${{ env.workspace_git }}/source/${{github.event.inputs.filename}} ${{env.GH_WS}}
              env:
                GH_WS: ${{ env.workspace_git }}
              shell: bash
